import { Submission } from "@/app/model/submission";
import { NextApiRequest, NextApiResponse } from "next";

const submissions: Submission[] = [
  {
    id: 1,
    name: "John Doe",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 40,
    fineTuningLanguageModel: 35,
    multiModelAIIntegration: 40,
    python: 30,
    aIModel: 25,
    analysingUserFeedback: 35,
    problemSolving: 40,
    teamWork: 40,
    motivation: 35,
  },
  {
    id: 2,
    name: "Jane Smith",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 75,
    fineTuningLanguageModel: 70,
    multiModelAIIntegration: 80,
    python: 70,
    aIModel: 75,
    analysingUserFeedback: 65,
    problemSolving: 75,
    teamWork: 75,
    motivation: 70,
  },
  {
    id: 3,
    name: "Bob Johnson",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 65,
    fineTuningLanguageModel: 50,
    multiModelAIIntegration: 65,
    python: 60,
    aIModel: 60,
    analysingUserFeedback: 55,
    problemSolving: 70,
    teamWork: 65,
    motivation: 60,
  },
  {
    id: 4,
    name: "Sharon Roberge",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 95,
    fineTuningLanguageModel: 80,
    multiModelAIIntegration: 100,
    python: 90,
    aIModel: 95,
    analysingUserFeedback: 90,
    problemSolving: 100,
    teamWork: 95,
    motivation: 90,
  },
  {
    id: 5,
    name: "Sonia Doe",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 40,
    fineTuningLanguageModel: 35,
    multiModelAIIntegration: 40,
    python: 30,
    aIModel: 25,
    analysingUserFeedback: 35,
    problemSolving: 40,
    teamWork: 40,
    motivation: 35,
  },
  {
    id: 6,
    name: "Mark Smith",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 95,
    fineTuningLanguageModel: 80,
    multiModelAIIntegration: 100,
    python: 90,
    aIModel: 95,
    analysingUserFeedback: 90,
    problemSolving: 100,
    teamWork: 95,
    motivation: 90,
  },
  {
    id: 7,
    name: "Alice Johnson",
    submissionTime: "2021-09-01T12:00:00Z",
    overallScore: 0,
    overallRating: "",
    ragImplementation: 75,
    fineTuningLanguageModel: 70,
    multiModelAIIntegration: 80,
    python: 70,
    aIModel: 75,
    analysingUserFeedback: 65,
    problemSolving: 75,
    teamWork: 75,
    motivation: 70,
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json(submissions);
}
