import { Submission } from "@/app/model/submission";
import { NextApiRequest, NextApiResponse } from "next";

const submissions: Submission[] = [
  {
    project: "Binoloop",
    submissions: [
      {
        id: 1,
        name: "John Doe",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 40,
        fineTuningLanguageModel: 35,
        multiModelAIIntegration: 40,
        python: 30,
        aIModel: 25,
        analysingUserFeedback: 35,
        problemSolving: 40,
        teamWork: 40,
        motivation: 35,
      },
      {
        id: 2,
        name: "Jane Smith",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 75,
        fineTuningLanguageModel: 70,
        multiModelAIIntegration: 80,
        python: 70,
        aIModel: 75,
        analysingUserFeedback: 65,
        problemSolving: 75,
        teamWork: 75,
        motivation: 70,
      },
      {
        id: 3,
        name: "Bob Johnson",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 65,
        fineTuningLanguageModel: 50,
        multiModelAIIntegration: 65,
        python: 60,
        aIModel: 60,
        analysingUserFeedback: 55,
        problemSolving: 70,
        teamWork: 65,
        motivation: 60,
      },
      {
        id: 4,
        name: "Sharon Roberge",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 95,
        fineTuningLanguageModel: 80,
        multiModelAIIntegration: 100,
        python: 90,
        aIModel: 95,
        analysingUserFeedback: 90,
        problemSolving: 100,
        teamWork: 95,
        motivation: 90,
      },
      {
        id: 5,
        name: "Sonia Doe",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 40,
        fineTuningLanguageModel: 35,
        multiModelAIIntegration: 40,
        python: 30,
        aIModel: 25,
        analysingUserFeedback: 35,
        problemSolving: 40,
        teamWork: 40,
        motivation: 35,
      },
      {
        id: 6,
        name: "Mark Smith",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 95,
        fineTuningLanguageModel: 80,
        multiModelAIIntegration: 100,
        python: 90,
        aIModel: 95,
        analysingUserFeedback: 90,
        problemSolving: 100,
        teamWork: 95,
        motivation: 90,
      },
      {
        id: 7,
        name: "Alice Johnson",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 75,
        fineTuningLanguageModel: 70,
        multiModelAIIntegration: 80,
        python: 70,
        aIModel: 75,
        analysingUserFeedback: 65,
        problemSolving: 75,
        teamWork: 75,
        motivation: 70,
      },
    ],
  },
  {
    project: "Project 1",
    submissions: [
      {
        id: 1,
        name: "Rhea Johnson",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 40,
        fineTuningLanguageModel: 39,
        multiModelAIIntegration: 30,
        python: 70,
        aIModel: 45,
        analysingUserFeedback: 65,
        problemSolving: 35,
        teamWork: 25,
        motivation: 30,
      },
      {
        id: 2,
        name: "Bob Marley",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 60,
        fineTuningLanguageModel: 70,
        multiModelAIIntegration: 65,
        python: 62,
        aIModel: 55,
        analysingUserFeedback: 60,
        problemSolving: 70,
        teamWork: 62,
        motivation: 55,
      },
      {
        id: 3,
        name: "Franklin Roosevelt",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 70,
        fineTuningLanguageModel: 80,
        multiModelAIIntegration: 90,
        python: 95,
        aIModel: 87,
        analysingUserFeedback: 89,
        problemSolving: 92,
        teamWork: 98,
        motivation: 90,
      },
    ],
  },
  {
    project: "Project 2",
    submissions: [
      {
        id: 1,
        name: "Samuel Johnson",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 55,
        fineTuningLanguageModel: 67,
        multiModelAIIntegration: 80,
        python: 35,
        aIModel: 45,
        analysingUserFeedback: 78,
        problemSolving: 35,
        teamWork: 25,
        motivation: 25,
      },
      {
        id: 2,
        name: "Victor Marley",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 56,
        fineTuningLanguageModel: 50,
        multiModelAIIntegration: 80,
        python: 85,
        aIModel: 90,
        analysingUserFeedback: 95,
        problemSolving: 90,
        teamWork: 89,
        motivation: 92,
      },
      {
        id: 3,
        name: "Oliver Roosevelt",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 70,
        fineTuningLanguageModel: 80,
        multiModelAIIntegration: 90,
        python: 95,
        aIModel: 87,
        analysingUserFeedback: 89,
        problemSolving: 92,
        teamWork: 98,
        motivation: 90,
      },
      {
        id: 4,
        name: "Liam Adams",
        submissionTime: "2021-09-01T12:00:00Z",
        overallScore: 0,
        overallRating: "",
        ragImplementation: 45,
        fineTuningLanguageModel: 50,
        multiModelAIIntegration: 55,
        python: 45,
        aIModel: 35,
        analysingUserFeedback: 30,
        problemSolving: 45,
        teamWork: 50,
        motivation: 40,
      },
    ],
  },
];

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json(submissions);
}
